    name: CI Voyage App

    on:
      push:
        branches: [ develop, main ]
      pull_request:
        branches: [ develop, main ]
      workflow_dispatch:   # permet de lancer manuellement depuis GitHub Actions

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - uses: subosito/flutter-action@v2
            with:
              channel: 'stable'

          - name: Créer .env
            run: |
              echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
              echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env

          - run: flutter pub get

          - run: flutter analyze --no-fatal-infos --no-fatal-warnings

      sast_scan:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Run Semgrep (SAST)
            run: |
              pip install semgrep
              semgrep --config=auto

      sca_scan:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Run Trivy (SCA)
            uses: aquasecurity/trivy-action@master
            with:
              scan-type: 'fs'
              severity: 'HIGH,CRITICAL'
              exit-code: '0'
              ignore-unfixed: true

      dast_scan:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: subosito/flutter-action@v2
            with:
              channel: 'stable'
          - name: Créer .env
            run: |
              echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
              echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
          - name: Activer Flutter web et démarrer le serveur
            run: |
              flutter config --enable-web
              flutter pub get
              flutter run -d web-server --web-port 8080 &
              sleep 30
          - name: Run OWASP ZAP baseline (DAST)
            continue-on-error: true
            run: |
              docker run --network host \
                -v ${{ github.workspace }}:/zap/wrk \
                ghcr.io/zaproxy/zaproxy:stable \
                zap-baseline.py \
                -t http://localhost:8080 \
                -r /zap/wrk/zap_report.html
          - name: Upload DAST report
            uses: actions/upload-artifact@v4
            with:
              name: zap-report
              path: zap_report.html



# ─────────────────────────────────────────
  # JOB 5 : CD - Générer et livrer l'APK
  # Se déclenche UNIQUEMENT sur main
  # et seulement si CI est tout vert
  # ─────────────────────────────────────────
  #deliver_apk:
    #name: CD - Générer et livrer l'APK
    #needs: [build, sast_scan, sca_scan]
    #runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/main'
 
    #steps:
     # - uses: actions/checkout@v4
 
     
    # - uses: subosito/flutter-action@v2
     #   with:
      #    channel: 'stable'
 
     # - name: Créer .env
      #  run: |
       #   echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
        #  echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
 
      #- run: flutter pub get
 
      #- name: Build APK release
       # run: flutter build apk --release --no-tree-shake-icons
 
      #- name: Upload APK
       # uses: actions/upload-artifact@v4
       # with:
        #  name: voyage-app-release
         # path: build/app/outputs/flutter-apk/app-release.apk
          