name: CI Voyage App

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:   # permet de lancer manuellement depuis GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Créer .env
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env

      - run: flutter pub get

      - run: flutter analyze --no-fatal-infos --no-fatal-warnings

  sast_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep (SAST)
        run: |
          pip install semgrep
          semgrep --config=auto

  sca_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
      - name: Run Trivy (SCA)
        run: ./trivy fs --severity HIGH,CRITICAL .

  dast_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run OWASP ZAP baseline (DAST)
        run: |
          docker run -t owasp/zap2docker-stable zap-baseline.py \
            -t http://localhost:8080 \
            -r zap_report.html
      - name: Upload DAST report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
